name: Simple Push Workflow

on:
  push:
    branches:
      - main # Może być również inna gałąź, np. 'develop'

jobs:
  simple_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Display the directory structure
      run: ls -alh  # Wyświetla strukturę katalogów w repozytorium

    - name: Run a simple echo command
      run: echo "Push detected! Workflow is running."

    - name: Display the current working directory
      run: pwd  # Wyświetla ścieżkę bieżącego katalogu roboczego
